version: '3.8'

services:
  hardhat:
    extends:
      file: ./services/docker-compose-l1hardhat.yml
      service: hardhat
    image: ${L1_DOCKER_TAG:-specularl2/hardhat:latest}
    container_name: hardhat

  sequencer:
    extends:
      file: ./services/docker-compose-sequencer.yml
      service: sequencer
    image: ${L2_DOCKER_TAG:-specularl2/l2geth:latest}
    depends_on:
      - hardhat
    links:
      - hardhat
    environment:
      SPECULAR_NODE_CFG_PATH: ./config/l2_node/integration_test_sequencer.toml
