version: '3.8'

services:
  sidecar:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    depends_on:
      l1-geth:
        condition: service_healthy
    volumes:
      - ../sbin:/sbin
      - ../workspace:/workspace
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_sidecar.sh

  sp-geth:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    env_file:
      ../workspace/.sp_geth.env
    volumes:
      - ../sbin:/sbin
      - ../workspace:/workspace
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_sp_geth.sh

  sp-magi:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    depends_on:
      l1-geth:
        condition: service_healthy
    # volumes:
    #   - ../sbin:/sbin
    #   - ../workspace:/workspace
    working_dir: /specular/workspace
    entrypoint: bash
    # ../sbin/start_sp_magi.sh

  l1-geth:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    healthcheck:
      test: ["CMD", "test", "-s", "/specular/workspace/l1.log"]
      retries: 10
      interval: 5s
      start_period: 20s
    # volumes:
    #   - ../sbin:/sbin
    #   - ../workspace:/workspace
    #   - ../config:/config
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_l1.sh -d
