version: '3.8'

services:
  sidecar:
    image: ${L2_DOCKER_TAG:-specularl2/sidecar:latest}
    build:
      context: ..
      dockerfile: ./services/sidecar/Dockerfile
    volumes:
      - ../sbin:/sbin
      - ../workspace:/workspace
    working_dir: /workspace
    entrypoint: sh ../sbin/start_sidecar.sh

  sp-geth:
    image: ${L2_DOCKER_TAG:-specularl2/sp-geth:latest}
    build:
      context: ../services/el_clients/go-ethereum
    env_file:
      ../workspace/.sp_geth.env
    volumes:
      - ../sbin:/sbin
      - ../workspace:/workspace
    working_dir: /workspace
    entrypoint: sh ../sbin/start_sp_geth.sh

  sp-magi:
    image: ${L2_DOCKER_TAG:-specularl2/sp-magi:latest}
    build:
      context: ../services/cl_clients/magi
    volumes:
      - ../sbin:/sbin
      - ../workspace:/workspace
    working_dir: /workspace
    entrypoint: sh ../sbin/start_sp_magi.sh

  l1-geth:
    image: ${L2_DOCKER_TAG:-specularl2/l1_geth:latest}
    build:
      context: ..
      dockerfile: ./docker/l1.Dockerfile
    volumes:
      - ../sbin:/sbin
      - ../workspace:/workspace
      - ../config:/config
    working_dir: /workspace
    entrypoint: sh ../sbin/start_l1.sh
