version: '3.8'

services:

  generator:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-latest
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: /bin/bash ../sbin/generate_secrets.sh -d -j -y

  l1-geth:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-latest
    healthcheck:
      test: bash -c "[ -f /tmp/.l1_started.lock ]"
      retries: 10
      interval: 5s
      start_period: 20s
    env_file:
      - ../workspace/.paths.env
      - ../workspace/.sp_geth.env
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: /bin/bash ../sbin/start_l1.sh -c -d -w -y
    depends_on:
      generator:
        condition: service_completed_successfully
    networks:
      - specular

  sp-geth:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-latest
    volumes:
      - sp_workspace:/specular/workspace
    restart: on-failure
    env_file:
      - ../workspace/.paths.env
      - ../workspace/.sp_magi.env
    depends_on:
      l1-geth:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /tmp/.sp_geth_started.lock ]"
      retries: 10
      interval: 5s
      start_period: 20s
    working_dir: /specular/workspace
    entrypoint: ../sbin/start_sp_geth.sh -c -w
    networks:
      - specular

  sp-magi:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-latest
    restart: on-failure
    depends_on:
      sp-geth:
        condition: service_healthy
    healthcheck:
      test: bash -c "[ -f /tmp/sp_magi_started.lock ]"
      retries: 10
      interval: 5s
      start_period: 20s
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_sp_magi.sh
    networks:
      - specular

  sidecar:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-latest
    restart: on-failure
    depends_on:
      sp-magi:
        condition: service_healthy
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_sidecar.sh
    networks:
      - specular

# shared volume and networks
volumes:
  sp_workspace:
    driver: local # Define the driver and options under the volume name

networks:
  specular:
    name: sp_network
