version: '3.8'

services:
  sequencer:
    extends:
      file: ./services/docker-compose-l2geth.yml
      service: l2geth
    container_name: sequencer
    ports:
      - 4011:8545
      - 4012:8546
    environment:
      SPECULAR_NODE_CFG_PATH: ./config/l2_node/docker_sequencer.toml
      IS_SEQUENCER: 1
