version: '3.8'

services:

  l1-geth:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    healthcheck:
      test: ["CMD", "test", "-s", "/workspace/l1_started.lock"]
      retries: 10
      interval: 5s
      start_period: 20s
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: yes |../sbin/generate_secrets.sh -d -j && yes ./sbin/start_l1.sh -c -d
    networks:
      - specular

  sp-geth:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: yes | ../sbin/start_sp_geth.sh -c
    networks:
      - specular

  sp-magi:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    depends_on:
      l1-geth:
        condition: service_healthy
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_sp_magi.sh
    networks:
      - specular

  sidecar:
    image: 792926601177.dkr.ecr.us-east-2.amazonaws.com/specular-platform:specular-v.0.01
    depends_on:
      l1-geth:
        condition: service_healthy
    volumes:
      - sp_workspace:/specular/workspace
    working_dir: /specular/workspace
    entrypoint: bash ../sbin/start_sidecar.sh
    networks:
      - specular

# shared volume and networks
volumes:
  sp_workspace:
    driver: local # Define the driver and options under the volume name

networks:
  specular:
    name: sp_network
