version: '3.8'

services:
  hardhat:
    extends:
      file: ./services/docker-compose-l1hardhat.yml
      service: hardhat
    container_name: hardhat

  sequencer:
    extends:
      file: ./services/docker-compose-l2geth.yml
      service: l2geth
    container_name: sequencer
    depends_on:
      - hardhat
    ports:
      - 4011:8545
      - 4012:8546
    links:
      - hardhat
    command:
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.api=personal,eth,net,web3,txpool,miner,proof,debug
      - --ws
      - --ws.port=8546
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=personal,eth,net,web3,txpool,miner,proof,debug
      - --rollup.node=sequencer
      - --rollup.coinbase=f39fd6e51aad88f6f4ce6ab8827279cfffb92266
      - --rollup.l1endpoint=ws://hardhat:8545
      - --rollup.l1chainid=31337
      - --rollup.sequencer-inbox-addr=0x2E983A1Ba5e8b38AAAeC4B440B9dDcFBf72E15d1
      - --rollup.rollup-addr=0xF6168876932289D073567f347121A267095f3DD6
      - --rollup.rollup-stake-amount=100
