[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]
test = 'test'
cache_path  = 'forge-cache'

[fmt]
line_length = 120

[fuzz]
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config