name: 'Setup Foundry'

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run forge install
      run: forge install
      shell: bash