name: 'Build foundry'

runs:
  using: "composite"
  steps:
    - name: Cache Foundry toolchain
      uses: actions/cache@v2
      with:
        path: ~/.foundry
        key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
        restore-keys: |
          ${{ runner.os }}-foundry-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run forge install
      shell: bash
      run: forge install
