apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.specular.service: sp-geth
  name: sp-geth
spec:
  ports:
    - name: "4011"
      port: 4011
      targetPort: 4011
    - name: "4012"
      port: 4012
      targetPort: 4012
    - name: "4013"
      port: 4013
      targetPort: 4013
  selector:
    io.specular.service: sp-geth
