version: '3.8'

services:
  geth:
    image: ethereum/client-go
    ports:
      - 8545:8545
    command: --dev --dev.period 1 --verbosity 3 --http --http.api eth,web3,net --http.addr 0.0.0.0 --ws --ws.api eth,net,web3 --ws.addr 0.0.0.0 --ws.port 8545

