version: '3.8'

services:
  l2geth:
    image: specularl1/l2geth:${DOCKER_TAG:-latest}
    build:
      context: ../..
      dockerfile: ./clients/geth/specular/Dockerfile
    volumes:
      - ${SPECULAR_DATADIR:-$PWD/specular-datadir}:/specular
    env_file:
      - ../envs/common.env
    entrypoint: geth.sh
