version: '3.8'

services:
  l2geth:
    image: ${L2_DOCKER_TAG:-specularl2/l2geth:latest}
    build:
      context: ../..
      dockerfile: ./clients/geth/specular/Dockerfile
    volumes:
      - ${SPECULAR_DATADIR:-$PWD/specular-datadir}:/specular
    env_file:
      - ../envs/common.env
    entrypoint: geth.sh
