name: e2e

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:
      - name: Check machine OS
        run: |
          echo "Machine OS: ${{ runner.os }}"

      - name: Check Docker version
        run: |
          docker version

      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.5.1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: ./.github/actions/node

      - name: Setup Testing Environment
        run: ./e2e/sbin/setup.sh

      - name: Build Container # TODO: Cache it
        run: ./e2e/sbin/build-container.sh

      - name: Run Test
        run: ./e2e/sbin/test.sh

