name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        test-name: ['transactions', 'deposit', 'withdraw', 'erc20']
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    steps:
      - name: Cache git folder
        uses: actions/cache@v3
        with:
          path: ./.git
          key: git-folder

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: ./.github/actions/node

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Testing Environment
        run: ./e2e/sbin/setup.sh

      - name: Run Test
        run: ./e2e/sbin/test.sh ${{ matrix.test-name }}
