name: e2e

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:
      - name: Check machine OS
        run: |
          echo "Machine OS: ${{ runner.os }}"

      - name: Check Docker version
        run: |
          docker version

      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.5.1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Create proj folder and add keys and genesis.json
        run: |
          mkdir project && cd project
          mkdir specular-datadir && cd specular-datadir
          cp ../../clients/geth/specular/data/keys/sequencer.prv ./key.prv
          cp ../../clients/geth/specular/data/password.txt .
          cd ../../contracts/ && npx hardhat compile && npx ts-node scripts/create_genesis.ts --in ../clients/geth/specular/data/base_genesis.json --out ../project/specular-datadir/genesis.json

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Start up containers
        run: |
          cd project
          rm -rf specular-datadir/geth/
          docker-compose -f ../docker/docker-compose-integration-test.yml up -d --build
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          sleep 30
          ./wait-for-it.sh -t 240 127.0.0.1:8545
          ./wait-for-it.sh -t 240 127.0.0.1:4011

      - name: Run testing script
        run: |
          cd contracts
          npx ts-node scripts/testing.ts

      - name: Stop and remove containers
        run: |
          docker-compose -f docker/docker-compose-integration-test.yml down
