name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
  lint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v3

      - name: Cache Foundry toolchain
        uses: actions/cache@v2
        with:
          path: ~/.foundry
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          timeout-minutes: 5
          version: nightly

      - name: Run forge install
        run: forge install

      - name: Check if forge fmt was run
        run: forge fmt --check
