name: Build and release

on:
  push:
    branches:
      - develop
      - macwis/release-artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Cache git folder
        uses: actions/cache@v3
        with:
          path: ./.git
          key: git-folder

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: ./.github/actions/node

      - uses: ./.github/actions/foundry

      - uses: ./.github/actions/go

      - name: Make specular
        run: make

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: true
          artifacts: "artifacts/*"
