name: Slither Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
  analyze:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/node
      
      - name: Generate Lock File
        working-directory: ./contracts
        run: pnpm make-dedicated-lockfile

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          sarif: results.sarif
          node-version: 16
          target: ./contracts
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: github.repository == 'SpecularL2/specular'
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
