name: Slither Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze-slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
      
      - name: Generate lock file
        working-directory: ./contracts
        run: pnpm make-dedicated-lockfile

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        working-directory: ./contracts
        id: slither
        with:
          slither-version: 0.9.6
          sarif: results.sarif
          node-version: 16
          fail-on: none
          slither-args: '--filter-paths "(lib/|@openzeppelin|hardhat|src/libraries/BytesLib.sol|test/)"'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: github.repository == 'SpecularL2/specular'
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
