name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v3

      - name: Skip build if duplicate
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: same_content_newer

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run forge install
        run: forge install

      # - name: Run tests
      #   env:
      #     RPC_URL: ${{ secrets.RPC_URL }}
      #   run: forge test -vvv
